#!/bin/bash

if [ -z "$(command -v "flake8")" ];
then
    echo "[pre-commit/flake8] Unable to execute! 'flake8' not found!" >&2
    echo "Please install 'flake8', either from the system package manager, e.g." >&2
    echo -e "\tsudo apt install -y python3-flake8" >&2
    echo "or via the Python Package Manager:" >&2
    echo -e "\tpip install flake8"
fi

echo "Checking for flake8 violations..." >&2
flake8 \
    $(git rev-parse --show-toplevel)/src \
    $(git rev-parse --show-toplevel)/test
FLAKE8_RESULT=$?

if [ $FLAKE8_RESULT -ne 0 ];
then
    echo "[pre-commit/flake8] flake8 violations found! Refusing to commit..." >&2
    exit 1
fi
