#!/bin/bash

if [ -z "$(command -v "pycodestyle")" ];
then
    echo "[pre-commit/pycodestyle] Unable to execute! 'pycodestyle' not found!" >&2
    echo "Please install 'pycodestyle', either from the system package manager, e.g." >&2
    echo -e "\tsudo apt install -y pycodestyle" >&2
    echo "or via the Python Package Manager:" >&2
    echo -e "\tpip install pycodestyle"
    exit 1
fi

echo "Checking for pycodestyle violations..." >&2
pycodestyle $(git rev-parse --show-toplevel)
PYCODESTYLE_RESULT=$?

if [ $PYCODESTYLE_RESULT -ne 0 ];
then
    echo "[pre-commit/pycodestyle] pycodestyle violations found! Refusing to commit..." >&2
    exit 1
fi
